
const skillsSet = [
  { name: "Javascript", important: true },
  { name: "React", important: true },
  { name: "Redux", important: true },
  { name: "Node.js", important: true },
  { name: "Express.js", important: true },
  { name: "CSS 3", important: true },
  { name: "CSS Flexbox", important: false },
  { name: "CSS Grid", important: false },
  { name: "HTML 5", important: true },
  // { name: "NPM", important: false },
  // { name: "Yarn", important: false },
  // { name: "Bootstrap", important: false },
  // { name: "JQuery", important: false },
  { name: "Linux Shell", important: false },
  // { name: "Lodash", important: false },
  { name: "Mongoose", important: false },
  { name: "Java SE 8", important: true },
  { name: "Ejs", important: false },
  { name: "MongoDB", important: true },
  { name: "PostgreSQL", important: true },
  // { name: "MongoDB Atlas", important: false },
  { name: "Firebase", important: true },
  { name: "OAuth2", important: false },
  { name: "Passport.js", important: false },
  { name: "Fetch API", important: true },
  { name: "Axios", important: true },
  // { name: "MailChimp", important: false },
  // { name: "Heroku", important: false },
  // { name: "Netlify", important: false },
  // {name: "Vercel", important: false},
  { name: "Git/GitHub", important: true },
  { name: "Next.js", important: true },
  { name: "Sass", important: true },
  { name: "Styled Components", important: false },
  { name: "RapidAPI", important: false },
  { name: "Agile (Scrum, Kanban)", important: true},
  { name: "Tailwind CSS", important: false },
  // { name: "Material UI", important: false },
  // { name: "Framer-Motion", important: false },
  { name: "TypeScript", important: true },
  // { name: "Selenium", important: true },
  { name: "Docker", important: true },
  { name: "Kubernetes", important: true },
  // { name: "RabbitMQ", important: true },
  { name: "Figma", important: true },
  { name: "Jira", important: true }
];


export default skillsSet;